import { AlertTriangle, CheckCircle2, Clipboard, KeyRound, ShieldAlert, Activity, Clock3 } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";

type AnyRecord = Record<string, unknown>;
const asArray = <T,>(value: unknown) => Array.isArray(value) ? value as T[] : [];
const text = (value: unknown, fallback = "Unknown") => typeof value === "string" && value.trim() ? value : fallback;
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const dateLabel = (value: unknown) => { const date = value ? new Date(String(value)) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString() : "Recent"; };

function StatCard({ label, value, detail, tone = "default" }: { label: string; value: string; detail: string; tone?: "default" | "good" | "warn" }) {
  const color = tone === "good" ? "text-[#a5f763]" : tone === "warn" ? "text-amber-200" : "text-zinc-100";
  return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4 transition hover:-translate-y-0.5 hover:border-[#8ee53f]/25 hover:bg-white/[.04]"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-zinc-600">{label}</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${color}`}>{value}</p><p className="mt-1 text-xs text-zinc-500">{detail}</p></div>;
}

export function FounderSecurityObservability() {
  const keys = trpc.admin.apiKeys.useQuery({});
  const events = trpc.admin.auditEvents.useQuery({ limit: 40 });
  const requests = trpc.admin.requestLogs.useQuery({ limit: 80 });
  const [copied, setCopied] = useState<string | null>(null);
  const keyRows = asArray<AnyRecord>(keys.data);
  const eventRows = asArray<AnyRecord>(events.data);
  const requestRows = asArray<AnyRecord>(requests.data);
  const activeKeys = keyRows.filter(row => row.isActive !== false && row.status !== "revoked");
  const violationRows = eventRows.filter(row => { const kind = `${row.eventType ?? ""} ${row.type ?? ""}`.toLowerCase(); return /(violation|denied|rate.?limit|quarantine|banned|failed|invalid|blocked|security)/.test(kind); });
  const usage = useMemo(() => {
    const buckets = new Map<string, { success: number; error: number }>();
    requestRows.forEach(row => { const raw = row.createdAt ?? row.timestamp ?? row.created_at; const date = raw ? new Date(String(raw)) : new Date(); const key = Number.isNaN(date.getTime()) ? "Recent" : date.toLocaleDateString(undefined, { month: "short", day: "numeric" }); const bucket = buckets.get(key) ?? { success: 0, error: 0 }; if (String(row.status ?? row.statusCode ?? "").startsWith("2") || row.status === "success") bucket.success += 1; else bucket.error += 1; buckets.set(key, bucket); });
    return Array.from(buckets.entries()).slice(-7);
  }, [requestRows]);
  const maxUsage = Math.max(1, ...usage.map(([, row]) => row.success + row.error));
  const copyKey = async (value: string, id: string) => { try { await navigator.clipboard.writeText(value); setCopied(id); window.setTimeout(() => setCopied(null), 1400); } catch { setCopied(null); } };
  const loading = keys.isLoading || events.isLoading || requests.isLoading;
  return <section aria-label="Founder API security observability" className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#a5f763]">Security observability</p><h2 className="mt-1 text-xl font-semibold text-zinc-100">API access posture</h2><p className="mt-1 max-w-2xl text-sm text-zinc-500">Monitor real API-key usage, policy signals, and recent security activity from Neon-backed records.</p></div><div className="flex items-center gap-2 rounded-full border border-[#8ee53f]/20 bg-[#8ee53f]/[.05] px-3 py-1.5 text-xs text-[#b5ff77]"><CheckCircle2 className="size-3.5" />Founder-only view</div></div>
    {loading ? <div role="status" aria-label="Loading security observability" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-24 animate-pulse rounded-2xl border border-white/8 bg-white/[.035]" />)}</div> : <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active API keys" value={String(activeKeys.length)} detail={`${keyRows.length} total records`} tone="good" /><StatCard label="Policy signals" value={String(violationRows.length)} detail="Recent security-related events" tone={violationRows.length ? "warn" : "good"} /><StatCard label="Requests observed" value={String(requestRows.length)} detail="Latest request-log window" /><StatCard label="Error rate" value={`${requestRows.length ? Math.round((requestRows.filter(row => row.status === "error" || number(row.statusCode) >= 400).length / requestRows.length) * 100) : 0}%`} detail="Within the visible window" tone={requestRows.some(row => row.status === "error") ? "warn" : "good"} /></div>
      <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
        <div className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100">Request activity</h3><p className="mt-1 text-xs text-zinc-600">Success and error volume from recent Neon request logs.</p></div><Activity className="size-4 text-[#a5f763]" /></div>{usage.length ? <div className="flex h-44 items-end gap-2">{usage.map(([label, row]) => { const total = row.success + row.error; return <div key={label} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-32 w-full max-w-12 items-end gap-0.5 rounded-t-lg bg-white/[.03] p-1"><div title={`${row.success} successful`} className="w-1/2 rounded-t bg-[#8ee53f]" style={{ height: `${Math.max(4, (row.success / maxUsage) * 100)}%` }} /><div title={`${row.error} errors`} className="w-1/2 rounded-t bg-amber-300/80" style={{ height: `${Math.max(row.error ? 4 : 0, (row.error / maxUsage) * 100)}%` }} /></div><span className="max-w-full truncate text-[10px] text-zinc-600">{label}</span><span className="text-[10px] text-zinc-500">{total}</span></div>; })}</div> : <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-zinc-600">No request activity has been recorded in the current window.</p>}</div>
        <div className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100">Policy signals</h3><p className="mt-1 text-xs text-zinc-600">Recent events requiring founder attention.</p></div><ShieldAlert className="size-4 text-amber-200" /></div>{violationRows.length ? <div className="space-y-2">{violationRows.slice(0, 5).map((row, index) => <div key={String(row.id ?? index)} className="flex items-start gap-2 rounded-xl border border-amber-200/10 bg-amber-200/[.03] p-3"><AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-amber-200" /><div className="min-w-0"><p className="truncate text-xs font-medium text-zinc-200">{text(row.eventType ?? row.type, "Security event")}</p><p className="mt-1 text-[10px] text-zinc-600">{dateLabel(row.createdAt ?? row.timestamp)}</p></div></div>)}</div> : <div className="flex items-center gap-2 rounded-xl border border-[#8ee53f]/10 bg-[#8ee53f]/[.03] p-4 text-xs text-[#b5ff77]"><CheckCircle2 className="size-4" />No recent policy violations detected.</div>}</div>
      </div>
      <div className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100">API-key inventory</h3><p className="mt-1 text-xs text-zinc-600">Masked records only. Stored secrets are never returned to the browser.</p></div><KeyRound className="size-4 text-[#a5f763]" /></div>{keyRows.length ? <div className="grid gap-2 md:grid-cols-2">{keyRows.slice(0, 12).map((row, index) => { const id = String(row.id ?? index); const name = text(row.name, "Unnamed key"); const prefix = text(row.keyPrefix ?? row.prefix, "kiwi_sk"); const lastFour = text(row.lastFour ?? row.last4, "••••"); const active = row.isActive !== false && row.status !== "revoked"; const copyValue = `${prefix}••••${lastFour}`; return <div key={id} className="group flex items-center justify-between gap-3 rounded-xl border border-white/8 bg-black/10 p-3 transition hover:border-[#8ee53f]/30 hover:bg-[#8ee53f]/[.03]"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${active ? "bg-[#8ee53f]" : "bg-zinc-600"}`} /><p className="truncate text-xs font-medium text-zinc-200">{name}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold uppercase ${active ? "bg-[#8ee53f]/10 text-[#b5ff77]" : "bg-white/[.06] text-zinc-500"}`}>{active ? "Active" : "Revoked"}</span></div><p className="mt-1 font-mono text-[10px] text-zinc-600">{prefix}••••{lastFour}</p></div><Button variant="ghost" size="icon" aria-label={`Copy masked identifier for ${name}`} title="Copy masked identifier" onClick={() => copyKey(copyValue, id)}>{copied === id ? <CheckCircle2 className="size-3.5 text-[#a5f763]" /> : <Clipboard className="size-3.5" />}</Button></div>; })}</div> : <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-zinc-600">No API-key records found.</p>}</div>
      <div className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold text-zinc-100">Recent activity</h3><p className="mt-1 text-xs text-zinc-600">Latest user actions and security events with safe metadata only.</p></div><Clock3 className="size-4 text-[#a5f763]" /></div>{eventRows.length ? <div className="divide-y divide-white/6">{eventRows.slice(0, 12).map((row, index) => <div key={String(row.id ?? index)} className="flex items-center justify-between gap-3 py-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-white/[.04] text-zinc-500"><Activity className="size-3.5" /></span><div className="min-w-0"><p className="truncate text-xs font-medium text-zinc-200">{text(row.eventType ?? row.type, "Activity")}</p><p className="mt-1 truncate text-[10px] text-zinc-600">{text(row.actorEmail ?? row.actor, "Founder or system")} · {dateLabel(row.createdAt ?? row.timestamp)}</p></div></div><span className="hidden rounded-full border border-white/8 px-2 py-1 text-[10px] text-zinc-600 sm:inline-flex">Recorded</span></div>)}</div> : <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-zinc-600">No recent activity events found.</p>}</div>
    </>}
  </section>;
}

export default FounderSecurityObservability;
